### ISSUE TITLE
Software Download?

### ISSUE THREAD

**Issue by olikraus** [dherrendoerfer/The-Robin-3D-Printer-Project#1]
Hi

Danke für das nette Gespräch von vorhin auf der Mini Make.
Aber: Wo gibt es denn die von Dir angesprochene modifizierte Software für den Bad Robin?
Ich hab hier leider keinen Link gefunden.

Danke, Oliver

**Comment by dherrendoerfer** [comment]
Die Firmware ist hier zu finden:
https://github.com/dherrendoerfer/The-Robin-3D-Printer-Project/tree/master/STL-Files/Bad-Robin/Firmware

**Comment by olikraus** [comment]
:+1: Danke
