### ISSUE TITLE
"ITEM 40mm aluminium profile"?

### ISSUE THREAD

**Issue by olikraus** [dherrendoerfer/The-Robin-3D-Printer-Project#2]
Hallo (ich schon wieder)

Was ist denn das "ITEM 40mm aluminium profile"?

Ist damit das Profile 8 gemeint?
https://product.item24.de/produkte/produktkatalog/products/konstruktionsprofile-8-1001042794/

Genauer: Das Profile 8 40x40 leicht, natur?

Danke & Grüße
Oliver

**Comment by dherrendoerfer** [comment]
Ja, ich kaufe immer das hier:
https://www.ebay.de/itm/ALU-Profil-Aluprofil-40x40-Nut-8-Aluminium-Profil-AlClipTec-item-kompatibel/261818937804?ssPageName=STRK%3AMEBIDX%3AIT&var=560678738966&_trksid=p2060353.m2749.l2649

Ich habe uebrigens z.Zt. seed-Kits (gruen), und es wird am JFZ eine Sammelbestellung Anfang 2019 geben.

**Comment by olikraus** [comment]
Ah guter link.

Was ist denn ein seed-Kit?

Mein größtes Problem sind eigentlich noch die auszudruckenden Teile vom Bad-Robin. 

naja, auch für den "Timing belts with 2xdriver (T2)" hab ich noch keine bezugsquelle gefunden.

Wie kommt denn das JFZ an die geprintenten Teile?

**Comment by dherrendoerfer** [comment]
Ein seed-kit ist ein Komplett-Set der gedruckten Teile. Diese sind leicht zu erkennen, weil sie grell grün sind. Wer ein seed-kit  bekommt verspricht mir im Gegenzug mindestens zwei Kits zurückzugeben, damit ich sie weitergeben kann. 
Das JFZ bekommt Teile z. Zt. auch von mir.

**Comment by olikraus** [comment]
ahhh... das wäre also genau das was ich bräuchte :-)

Das hört sich nach einem guten Deal an. Also, ich wäre dabei. Dann würde ich mal in den nächsten Tagen das BOM zusammenstellen (inkl. Bezugsquellen) und mich dann nochmal melden?

mein e-mail ist übrigens: olikraus_@_gmail_._com (ohne _)

**Comment by olikraus** [comment]
Ich habe jetzt gestern das zugehörige Video angeschaut. Soweit ist (fast) alles klar. Drei Fragen habe ich noch:
1. Der verwendete PTFE Tube: Innendurchmesser müsste 2mm sein, aber welchen aussendurchmesser hat denn der denn? 4mm?
2. Die NEMA17 motoren: Die gibt es in verschiedenen Stärken und Tiefen. Ich habe mal diesen hier ausgesucht:https://www.ebay.com/itm/Nema-17-Stepper-Motor-Bipolar-42mm-Hybrid-Two-Phase-42SHD0001-24-For-3D-Printer/332871755225
Wäre der ok?

Nun ja, wenn ich das Seed-Kit von Dir bekomme, würde ich mal loslegen mit der Bestellung.

**Comment by dherrendoerfer** [comment]
Solved.
