### ISSUE TITLE
z-axis m8 rod: BOM updates

### ISSUE THREAD

**Issue by olikraus** [dherrendoerfer/The-Robin-3D-Printer-Project#3]
Please excause another update request. 

"1x Threaded rod TR8 350mm long"

The actual length depends on the shaft length of the stepper motor. Maybe I have a stepper motor with long shaft, but for my setup, the rod must be only 340mm. I think it would be ok for any shaft length if the rod has only 340mm, so the update is to change the BOM entry to: "1x Threaded rod TR8 **340mm** long"

"1x Threaded rod nut TR8"

Actually this is a "long nut" with at least 12mm length. It would be cool if this is also mentioned: "1x Threaded rod **long** nut TR8 **with a minimal length of 12mm**"

Metal ball is not mentioned.

The metal ball (steel ball) which is placed below the M8 rod is not mentioned. At least it should be mentioned that either a bearing or the metal ball (3..5mm) has to be sourced:
"Z-axis bearing ball solution: 1x Bike stainless steel ball 3.5 to 4.5mm diameter"

**Comment by dherrendoerfer** [comment]
Thanks @olikraus 
I'll update this:

the correct length of the rod is 315mm when using the steel ball, and 320mm when using the bearing.
The TR8 Nut should be 17mm, or at least 12mm high
One steel ball bearing ball with 3.5 to 4.5mm diameter.

**Comment by dherrendoerfer** [comment]
I updated the BOM document, closing.
