### ISSUE TITLE
extruder heater and fan connection

### ISSUE THREAD

**Issue by olikraus** [dherrendoerfer/The-Robin-3D-Printer-Project#4]
I am a little bit confused.
As per the video, the extruder heater is connected to D10 and the fan to D9.

In the md file https://github.com/dherrendoerfer/The-Robin-3D-Printer-Project/blob/master/STL-Files/Bad-Robin/Build-Instructions.md the following is mentioned:

> Connect the extruder heater to E0
> Connect the extruder fan to E1, watch the polarity !

Probably it means the same because the heater of the first extruder is connected to D10. However, calling the first extrude E0 is also a little bit misleading, because the picture here https://reprap.org/wiki/File:Rampswire14.svg calls it extruder 1.

Suggestion is to change the description in the build instructions:

> Connect the extruder heater to D10
> Connect the extruder fan to D9, watch the polarity !

**Comment by dherrendoerfer** [comment]
Fixed with commit: https://github.com/dherrendoerfer/The-Robin-3D-Printer-Project/commit/65b15908f6b379d16c3a0390eba980823d689b62
