### ISSUE TITLE
Inductive proximity sensor output to Zmax should go through a 10K to 15K resistor

### ISSUE THREAD

**Issue by olikraus** [dherrendoerfer/The-Robin-3D-Printer-Project#5]
As stated in part 22 of the instructions (https://github.com/dherrendoerfer/The-Robin-3D-Printer-Project/blob/master/STL-Files/Bad-Robin/Build-Instructions.md) the level probe (Inductive proximity sensor) signal output should be connected to the z-max pin directly. 

However, this is dangerous:
1) The RAMPS board directly connects the z-max input pin with the uC without further protection.
2) The level probe sensor will deliver 12v as a active high signal, which will destroy the internal protection diode.

See also: https://www.avrfreaks.net/forum/12-volt-input-sigal-atmel-pin-make-logic-high

The signal output of the level probe sensor (usually the black line) should go to a 10K resistor, the other end of the 10K resistor is then connected to the z-max input of the RAMPS board.

This means, instead of
```
Connect the home switches

    X home switch to Xmin pin.
    Y home switch to Ymin pin.
    Z level probe (output) to Zmax
```

the description should be this:

```
Connect the home switches.

    X home switch to Xmin pin.
    Y home switch to Ymin pin.
    Z level probe (output, black line) to Zmax via 10K resistor 
```

Additionally, the BOM should mention the 10K resistor. BTW: The home switches are also not mentioned in the BOM.

**Comment by olikraus** [comment]
I have ordered exactly an "Inductive proximity switch PNP, NO(normally open)". The sensor, which I have received behaves exactly like a PNP senser. However:
 * I have to add an extra 10K resistor to protect the ATMega
 * I have to reconfigure the firmware
 * I have to add an external pull-down resistor

In other words, the BOM is wrong: Your 3D printer requires a NPN version of this sensor. If it is a NPN version, then indeed no further resistor is required. However, the PNP sensor, connected in the way as described in your video, will destroy the ATMega board (unless the 10K resistor is used).

**Comment by dherrendoerfer** [comment]
I fixed the BOM, I (in fact) did use a NPN, just copied it wrong.

So: If you have a PNP -> The above is the correct way to make it work .
Thanks!

**Comment by olikraus** [comment]
:+1:

**Comment by olikraus** [comment]
Just a small note:
for my PNP NO senser, i have a 100K pull-down and a 10K resistor in the dataline itself.

For this, I had to change the configuration (Configuration.h) like this:
```
#define ENDSTOP_PULLUP_Z_MIN false
#define ENDSTOP_Z_MIN_INVERTING false
...
#define ENDSTOP_Z_BACK_ON_HOME 1
```
